warp-ds/docs

docs/.vitepress/Footer.vue
docs/.vitepress/config.js
docs/.vitepress/theme/index.js
docs/help/report-bugs/index.md
docs/help/support/index.md

This PR replaces the previous footer that was defined in the `config.js`-file under `themeConfig.footer` with a customized footer.
- Create Footer.vue
- Use v-slot `layout-bottom` in the Layout() function in `.vitepress/theme/index.js` to make sure that the Footer component is displayed at the bottom of the layout. 
- Remove `themeConfig.footer` in config.js

feat(footer): add footer

---

docs/.vitepress/config.js
docs/components/alert/data.json
docs/components/alert/index.md
docs/components/avatar/data.json
docs/components/avatar/index.md
docs/components/badge/data.json
docs/components/badge/index.md
docs/components/box/data.json
docs/components/box/index.md
docs/components/breadcrumbs/data.json
docs/components/breadcrumbs/index.md
docs/components/buttons/data.json
docs/components/buttons/index.md
docs/components/card/data.json
docs/components/card/index.md
docs/components/checkbox/data.json
docs/components/checkbox/index.md
docs/components/index.md
docs/components/radio/data.json
docs/components/radio/index.md
docs/components/utils.js

This PR is an attempt to share repeated component data within the Components section. 
- added basic data about a few components in json format
- used this data to present description and framework status in respective component pages (added a helper function to util.js to map json data to ComponentStatuses props)
- used the same set of data to dynamically display a grid of component cards in the Component Overview page
- also added an Avatar component as an example of a Figma-only component
The data also contains a dynamically set url under `component.href` property, which can be used in the overview cards to navigate to correct component page.

feat(component-overview): reuse component metadata

---

docs/.vitepress/config.js
docs/.vitepress/theme/custom.css
docs/foundations/index.md
package.json

Adds a plugin called markdown-it-container, these makes it possible to define styleable custom markdown containers. 
Markdown syntax for the image block looks like this: 
`::: image-block`
`![Alt text go here](/css/matter.jpg)`
`:::`
Temporary styling:

Imageblock

---

docs/.vitepress/Card.vue
docs/.vitepress/Cards.vue
docs/components/alert/data.json
docs/components/index.md

To make te accessability stuff and also styling options viable I saw 2 solves
1. move  the content inside the component itself, looked to rigid and less likely we could reuse it for other things. 
2. (Chosen solve )move the content bit outside of the card, means more styling in the actual use of the component but I think that is fine since we are the only consumer of the thing. Allows alot of flexibility. 
This thing is styled with unoclasses for now.

change card structure to allow for accessability tweaks

---

docs/.vitepress/config.js

When the page is selected in the sidebar or in the navbar, its title is now correctly picking up selected style. The reason for this not working was a missing `/` at the end of the path. I checked that it's not an issue in foundations/styles/web pages, so I left those be.

fix(sidebar/navbar): fix selected page style

---

docs/.vitepress/theme/custom.css

Sets up a starting structure for us to add all our colors , and a place to map them to the --vp- tokens.
Sets up the documentsite to do dark/light switching based on user preferences on the device instead of a switch in the header.
When we have our colors in place we can remove all the .dark styling, that is all tied to the theme switch switch in the header, which can also be removed.

Add structure for warp colored tokens light-dark mode

---

docs/components/index.md

PAth in prod is apparently handled differently than dev env.   /./   <- had some of those in it.

fix broken picturepath in prod

---

docs/.vitepress/Footer.vue

fix(footer): add link to FAQ page

---

docs/index.md

We don't show anything under [foundations/tokens/](https://warp-ds.github.io/warp-portal-poc/foundations/tokens), because the actual content is located under [foundations/tokens/intro/](https://warp-ds.github.io/warp-portal-poc/foundations/tokens/intro/). This PR fixes the url :)

fix(home-page): fix url in the tokens card

---

docs/.vitepress/theme/custom.css

Tables now use the full width of their parent.
wrap a table in something class="table-container"  if your table cannot shrinc below mobile width, this will cause it to automagically get a horizontal scroll. 
Before: 
After:

Adjust table widths.

---

docs/.vitepress/config.js

This PR fixes a broken side-menu link to Icon Color page.
Part of [WARP-627](https://nmp-jira.atlassian.net/browse/WARP-627)

fix(config): fix icon color path

---

docs/.vitepress/config.js

This PR fixes the path to markdown files on Github when the "Edit this page" link is pressed on respective pages.
Part of [WARP-627](https://nmp-jira.atlassian.net/browse/WARP-627)

fix(config): remove '/src' from editLink path

---

docs/.vitepress/warp-theme-switcher.js

Just implying how light dark brand controll should be implemented :)   They can be optionally be called   finn/finn dark   when we add dark

Add light suffix to the themeswitch light choices

---

README.md
docs/.vitepress/config.js
docs/blog/posts.data.js
docs/blog/posts/2023/icons-v130.md
docs/blog/posts/2023/icons-v140.md
docs/blog/posts/2024/android-0.0.27.md
docs/blog/posts/2024/icons-v2.md
docs/components/ComponentOverview.vue
docs/index.md
package.json

Fixes [WARP-609](https://nmp-jira.atlassian.net/browse/WARP-609)
The docs will now be deployed to [warp-ds/docs](https://warp-ds.github.io/docs).

fix: rename warp-portal-poc do docs

---

package.json

We don't need the `docs:` prefix when docs is the only thing we work with here.

chore(scripts): drop docs: prefix in package scripts

---

docs/blog/posts/2024/warp-2-0.md
docs/collaborate/request-component-changes/index.md
docs/collaborate/request-new-component/index.md
docs/components/ComponentQuestions.md
docs/components/icons/index.md
docs/foundations/css-classes/divide-style.md
docs/foundations/css-classes/font-variant-numeric.md
docs/foundations/css-classes/max-width.md
docs/foundations/css-classes/scroll-snap-align.md
docs/foundations/css-classes/scroll-snap-stop.md
docs/foundations/css-classes/scroll-snap-type.md
docs/foundations/css-classes/will-change.md
docs/foundations/data-visualization/getting-started/index.md
docs/get-started/developers/android/index.md
docs/get-started/developers/ios/index.md
docs/get-started/developers/web/index.md
docs/help/report-bugs/index.md
docs/help/support/index.md
docs/index.md

Our slack channel was renamed so it should be reflected in our docs to avoid confusion. The Slack ID stays the same.

chore: update slack channel name to smp-warp-design-system

---

docs/foundations/brands/index.md

Fix broken links to brand documentation
Related slack issue:
[https://sch-chat.slack.com/archives/C04P0GYTHPV/p1736846986390319](https://www.google.com/url?q=https://sch-chat.slack.com/archives/C04P0GYTHPV/p1736846986390319&sa=D&source=calendar&ust=1738060595187478&usg=AOvVaw0ATA9f5fT1ZTZxOp9GVNJe)

Fix: broken links

---

docs/blog/posts/2025/icons-v260.md
package.json

Bumbs icons to 2.6.0, adding 5 new icons:
- car-left
- car-right
- plane-landing
- plane-take-off
- drag-dots
Add "What's new for icons"

Bump icons, update What's new

---

docs/.vitepress/theme/custom.css

Just sets up the titles rendered by markup to work the same as in figma, only different I could see was the devider line in the H2

Remove line on title2

---

docs/components/icons/elements.md

Couldn't find icons at `elements/components/<icon>`, but they were there on `elements/<icon>`.

Fix an import statement for elements icons

---

docs/foundations/typography/index.md

**Typography page (Warp Portal):** https://warp-ds.github.io/docs/foundations/typography/
Changes:
1. New Drive link to each typography
2. Fixed name of #uxwriting Slack channel

Fix Google Drive links on Typography page

---

docs/collaborate/request-component-changes/index.md
docs/collaborate/request-new-component/index.md
docs/foundations/accessibility/index.md
docs/foundations/css-classes/divide-style.md
docs/foundations/css-classes/font-variant-numeric.md
docs/foundations/css-classes/max-width.md
docs/foundations/css-classes/scroll-snap-align.md
docs/foundations/css-classes/scroll-snap-stop.md
docs/foundations/css-classes/scroll-snap-type.md
docs/foundations/css-classes/will-change.md
docs/foundations/data-visualization/introduction/index.md
docs/get-started/developers/android/index.md
docs/get-started/developers/ios/index.md
docs/get-started/developers/web/index.md
docs/get-started/developers/web/react.md
docs/get-started/developers/web/vue.md
docs/help/report-bugs/index.md
docs/help/support/index.md
docs/index.md

**Changes to Warp Portal:**
1. Replaced references to Warp's Slack channel from `#smp-warp-design-system` to `#warp-design-system`.
2. Replace reference to Accessibility Slack channel from `#smp-accessibility` to `#vend-accessibility`.
3. Changed Lukasz's profile photo to one from Slack.

Replace old Slack channel name with new one
